import { google } from "@ai-sdk/google";
import { streamText } from "ai";
import { z } from "zod";
import { requireUser } from "@/lib/auth/session";
import { authorizeDocument } from "@/lib/rbac/authorize";
import { handleError, readJson } from "@/lib/api/respond";
import { AppError } from "@/lib/rbac/errors";

/**
 * POST /api/ai/continue — AI "continue writing".
 *
 * Streams a continuation of the document from the caller's cursor position,
 * generated by Google Gemini via the Vercel AI SDK. The response is a plain
 * `text/plain` token stream the client inserts into the editor as it arrives.
 *
 * SECURITY:
 *   - Requires an authenticated session AND `document:write` on the document —
 *     VIEWERs (and guests) cannot spend AI quota or inject content.
 *   - The context is size-capped by Zod, so a malicious client cannot ship a
 *     huge prompt to the model.
 *   - The API key stays server-side (GOOGLE_GENERATIVE_AI_API_KEY); the browser
 *     never talks to Gemini directly.
 */

/**
 * Model is env-overridable (GEMINI_MODEL) so upgrades don't require a code
 * change. Default: gemini-3.5-flash — the free-tier Flash model as of Jul 2026
 * (gemini-2.5-flash was retired for new accounts on 2026-07-09).
 */
const MODEL = process.env.GEMINI_MODEL ?? "gemini-3.5-flash";

/** Hard cap on the context we forward to the model (characters). */
const MAX_CONTEXT_CHARS = 8_000;

/** Allow up to 30s of streaming on serverless platforms. */
export const maxDuration = 30;

const continueSchema = z.object({
  documentId: z.string().min(1),
  /** Plain text of the document BEFORE the cursor (the model's context). */
  context: z.string().max(MAX_CONTEXT_CHARS * 2), // pre-trim leniency
});

const SYSTEM_PROMPT = [
  "You are a writing assistant inside a collaborative document editor.",
  "Continue the user's document naturally from exactly where it stops.",
  "Match the existing tone, language, and formatting style.",
  "Return ONLY the continuation text — no preamble, no quotes, no markdown fences.",
  "Keep it concise: at most two short paragraphs unless the text clearly demands more.",
].join(" ");

export async function POST(request: Request) {
  try {
    const user = await requireUser();
    const { documentId, context } = await readJson(request, continueSchema);

    // Writers only — mirrors the RBAC rule for every other mutation.
    await authorizeDocument(user.id, documentId, "document:write");

    if (!process.env.GOOGLE_GENERATIVE_AI_API_KEY) {
      throw new AppError(
        "AI features are not configured.",
        500,
        "AI_NOT_CONFIGURED",
      );
    }

    // Keep only the tail of the context — the most relevant part for
    // continuation, and a bounded token spend per request.
    const prompt = context.slice(-MAX_CONTEXT_CHARS).trimStart();
    if (prompt.length === 0) {
      throw new AppError(
        "Write a few words first so the AI has something to continue.",
        400,
        "AI_EMPTY_CONTEXT",
      );
    }

    const result = streamText({
      model: google(MODEL),
      system: SYSTEM_PROMPT,
      prompt,
      /**
       * IMPORTANT (debuggability): streamText responds 200 immediately and by
       * default MASKS mid-stream errors (bad key, unknown model, quota) — the
       * client just sees an empty stream. Logging here makes the real cause
       * visible in the server terminal / Vercel logs.
       */
      onError: ({ error }) => {
        console.error("[ai/continue] generation failed:", error);
      },
    });

    // Plain text stream — trivially consumable with a ReadableStream reader.
    return result.toTextStreamResponse();
  } catch (err) {
    return handleError(err);
  }
}
